Add code to handle cdc usb devices
tectrolabs/swiftrng pull request #2
Opened 2020-03-29 23:51 UTC by tectrolabs

2020-03-29 23:54 UTC, tectrolabs commented
Made changes to support new SwiftRNG CDC class devices

2020-03-30 03:22 UTC, ebelinski requested changes
I found a few typos here and there. Looks good overall, although I had a hard time figuring out the nitty gritty of what some of the code actually does, since I'm not very familiar with the USB APIs here.

2020-03-30 03:22 UTC, ebelinski commented on windows-x64/SwiftRNG/USBComPort.cpp
> +This class implements the access to a SwiftRNG device over CDC USB interface on Windows platform.
```suggestion
This class implements access to a SwiftRNG device over CDC USB interface on Windows platform.
```

2020-03-30 03:22 UTC, ebelinski commented on windows-x64/SwiftRNG/USBComPort.cpp
> +	DWORD actualButesReceived;
Typo:

```suggestion
	DWORD actualBytesReceived;
```

2020-03-30 03:22 UTC, ebelinski commented on windows-x64/SwiftRNG/USBComPort.cpp
> +void USBComPort::initlalize() {
Typo:
```suggestion
void USBComPort::initialize() {
```

2020-03-30 03:22 UTC, ebelinski commented on windows-x64/SwiftRNG/swrngapi.cpp
> +int swrngOpen(SwrngContext *ctxt, int devNum) {
```suggestion
int swrngOpen(SwrngContext* ctxt, int devNum) {
```

2020-03-30 03:59 UTC, merged